context:
  name: jq.py
  pypi_name: jq
  version: "1.12.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ pypi_name[0] }}/${{ pypi_name }}/${{ pypi_name }}-${{ version }}.tar.gz
  sha256: 729b2d3418c8ca7dccfaa66b9fb7a98bec28474212650d27c5c04358ce26f55c

build:
  script: env JQPY_USE_SYSTEM_LIBS=1 python -m pip install . -vv
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython ==3.2.1
    - jq
  run:
    - python
    - jq

tests:
  - python:
      imports:
        - jq
      pip_check: true

about:
  homepage: https://github.com/mwilliamson/jq.py
  summary: Python bindings for jq
  description: |
    This project contains python bindings for jq, a lightweight and flexible
    JSON processor
  license: BSD-2-Clause
  license_file: LICENSE
  repository: https://github.com/mwilliamson/jq.py

extra:
  recipe-maintainers:
    - I-Al-Istannen
