context:
  version: "1.12.0"

package:
  name: jq.py
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jq/jq-${{ version }}.tar.gz
  sha256: 729b2d3418c8ca7dccfaa66b9fb7a98bec28474212650d27c5c04358ce26f55c

build:
  number: 0
  skip:
    - win
  script:
    env:
      JQPY_USE_SYSTEM_LIBS: "1"
    content:
      # make sure we're not using the vendored library
      - rm -r deps
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - cython ==3.2.3
    - setuptools >=43
    - pip
    - jq
  run:
    - python
    - jq

tests:
  - python:
      imports:
        - jq
      pip_check: true
  - requirements:
      run:
        - pytest
    files:
      source:
        - tests/
        - tox.ini
    script:
      - pytest

about:
  homepage: https://github.com/mwilliamson/jq.py
  summary: Python bindings for jq
  description: |
    This project contains python bindings for jq, a lightweight and flexible
    JSON processor
  license: BSD-2-Clause
  license_file: LICENSE
  repository: https://github.com/mwilliamson/jq.py

extra:
  recipe-maintainers:
    - I-Al-Istannen
    - mgorny
